module.exports = {
  emails: [
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
    {
      host: "smtp.gmail.com",
      port: 587,
      user: "email@gmail.com",
      pass: "password",
    },
  ],
};
